// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_content_delivery_bucket": "symbolorum",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://symbolorum.s3-website-eu-west-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "eu-west-1:4a4f0fe1-4374-4d59-8ab7-3dafb873f005",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_6DNZP715Z",
    "aws_user_pools_web_client_id": "1m5lp0rhf3ok48su8ia5ks7ed7"
};


export default awsmobile;
